version: '3.5'

services:
  postgres:
    container_name: postgres_odoo
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5431:5432"
    restart: unless-stopped

  odoo:
    container_name: odoo_app
    image: odoo:15.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    command: -- --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data: